version: '3.9'

services:
  database:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      some_network:

  webapi:
    image: webapi
    hostname: webapi
    build: ../
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    command: ./it_planet_task -dbAddr=db -dbUser=postgres -dbPass=123456 -dbName=postgres -dbPort=5432 -srvAddr=webapi -srvPort=8080
    networks:
      some_network:

networks:
  some_network:
    name: 'some_network'